up_block_types:
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
block_out_channels: [128, 256, 512, 512]

layers_per_block: 2
latent_channels: 4

skip_connections: false
skip_extra: false
d_skip_extra: 0
skip_zero: false

pretrained: True
pretrained_path: checkpoints/pretrained/autoencoder
